name: Deploy packages and apps

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: maxrsb/rsb-config:${{ github.sha }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2

      - name: Write kubeconfig to ~/.kube/config
        run: |
          mkdir ~/.kube
          echo '${{ secrets.KUBE_CONFIG }}' > ~/.kube/config

      - name: Terraform init, validate, plan and apply
        run: |
          cd infra
          echo "** Running Terraform Init**"
          terraform init

          echo "** Running Terraform Validate**"
          terraform validate

          echo "** Running Terraform Plan**"
          terraform plan -var="image_tag=${{ github.sha }}"

          echo "** Running Terraform Apply**"
          terraform apply -auto-approve -var="image_tag=${{ github.sha }}"